### ISSUE TITLE
Gifs Routing

### ISSUE THREAD

**Issue by zfrisch** [legomushroom/mojs-website#14]
In the Tutorial section for Shapes and Swirl you'll notice that the Gif Components don't render their images under 'Click Here To See The Gifs'(located right above the UI Examples). I believe it likely has to do with the Router you have setup. I was going to take a look and try to correct it myself, but I'm not familiar with CoffeeScript JSX and I feel that it's probably a minor fix. 

Excellent work so far! Greatly looking forward to this library!

**Comment by legomushroom** [comment]
@zfrisch hi! Thanks for the issue! Hmm, what browser/environment do you use? I can't quite get the issue.

Thanks a lot!

**Comment by zfrisch** [comment]
Sure! I'm running Chrome 52, IE 11, FF 47 on Windows. It seems to be an asset issue.

What I get is: 

![image](https://cloud.githubusercontent.com/assets/16858621/18216656/c1297c68-711d-11e6-9e6c-b14280d27ff1.png)

Which is perfectly fine, but on all browsers above, when I click I get this:

![image](https://cloud.githubusercontent.com/assets/16858621/18216669/da5bcc2c-711d-11e6-88fe-008d61fbb5df.png)

All browsers report the same thing, but here's Chrome's console(I don't have react dev tools because I'm on my work computer, apologies!)
![image](https://cloud.githubusercontent.com/assets/16858621/18216735/5c627e3c-711e-11e6-8279-661c40d209fd.png)


Hope that helps!

**Comment by legomushroom** [comment]
@zfrisch yeah it helps! thank you so much! fixed 🎉
