### ISSUE TITLE
Some header links download files instead of navigating.

### ISSUE THREAD

**Issue by bryanbraun** [legomushroom/mojs-website#19]
In the site header...
![image](https://cloud.githubusercontent.com/assets/1256329/18209306/35d8496c-7101-11e6-8659-981b5dbf8a1a.png)

Clicking "APIs", "Demos", or "Contribute" downloads an HTML file instead of navigating to the page. This is happing for me on multiple desktop browsers.

I think it might have something to do with the `download="false"` attribute that I'm seeing on the links. I'm thinking "false" is being interpreted as a filename string instead of a boolean. [Some docs](http://www.w3schools.com/tags/att_a_download.asp) suggest that might be the case.

It looks like [the code producing this attribute](https://github.com/legomushroom/mojs-website/blame/dev/app/partials/unite-link.cjsx#L14) is on the `dev` branch (not `master`), so I'm not sure where to contribute a fix. I also had some trouble getting the site to run locally so I don't have a PR for you. :(

**Comment by legomushroom** [comment]
@bryanbraun thanks for the issue! I knew about the issue but never had time to solve it. That's the `download attribute` indeed. You should always start from the `dev` branch to contribute. I can help you to run the site locally ( I think the Headroom component is the culprit for the issue and you can just comment it out ), or I will fix it myself in near future.  Please let me know!

**Comment by legomushroom** [comment]
@bryanbraun ok, fixed now! Thanks a lot! 🎉
